### ISSUE TITLE
Cannot find "Nuclide React Native: Start Debugging" command in the latest release.

### ISSUE THREAD

**Issue by Sam1301** [facebook/nuclide#1222]
### Issue and Steps to Reproduce
Steps to debug a react native involves:
1) start the packager using Nuclide React Native: Start Packager
2) start the debugger using Nuclide React Native: Start Debugging
3) run the app on simulator/device

After upgrading to latest version v0.236.0, I can't find the the start debugger command.

### Versions
* Atom: 1.18.0
* Nuclide: 0.236.0
* Client OS: macOS Sierra

**Comment by mostafaeweda** [comment]
React Native debugger support was dropped by https://github.com/facebook/nuclide/commit/fccd95d310d021ad67a6e524066bd9ab91e0e3ca
We intend to bring a better one back in the future

**Comment by Lastin** [comment]
Any updates on this?

**Comment by buschettu** [comment]
No news?

**Comment by Lastin** [comment]
I like how their website still says that it has react-native debugging capabilities.
![screenshot from 2017-10-04 10-49-10](https://user-images.githubusercontent.com/5638394/31169817-d268041a-a8f1-11e7-95f8-a5470c91dbc9.png)

**Comment by wuno** [comment]
So as of today there is no debugger support for react native?

**Comment by donaldcao** [comment]
Any update about it? or how can we debug RN app in Nuclide?

**Comment by wuno** [comment]
@donaldcao after researching with my team we found that they removed support from the package. So even though you can see it there, it is not usable for react native. There was talk here and there of them talking about putting it back in, but for now it does not look like something we can count on. in the meantime there are some cool tools out there that might help you out. Check this out - [Reactotron](https://github.com/infinitered/reactotron),

**Comment by donaldcao** [comment]
@wuno, but I mean the 'debug' functionality in Nuclide for RN, so still there is no one? or is there any plan to bring a new one as @said? or I must rely on Chrome RN dev-tool?

**Comment by wuno** [comment]
Yes. That was what I was talking about. I was just showing you that there are tools out there to try and make life easier. But not the ones that come with nuclide. Cause they do not work.

**Comment by donaldcao** [comment]
@wuno  Got it and thank you. but now it's really annoyed to edit in nuclide but debug in Chrome, nuclide seems likes a COMPLETE IDE for RN anymore, Many people are suffering from that I think. I need to find new one to replace it in these days. but anyway thank you wuno for your quick replay, have a good day~~

**Comment by mostafaeweda** [comment]
Debugging React Native is coming back to Nuclide next week & sorry that it had to be taken out due to low quality concerns.

**Comment by donaldcao** [comment]
@mostafaeweda That's really good news to the community! Look forward to trying this new better one.

**Comment by donaldcao** [comment]
@mostafaeweda, I saw you update nuclide related to debugger, so I pull the latest code and reinstall it in atom, but still I can't debug react native code, still only have Native option when I attach debugger, is there any new way to attach the debugger or something wrong with me?

**Comment by mostafaeweda** [comment]
That only came out today in https://github.com/facebook/nuclide/commit/0f47df4a2721c2f5456f2e310196efc3e6c71a7a — you can either build Nuclide from source or wait for next week’s release

**Comment by donaldcao** [comment]
OK, Got it and I will build it from source today. Thanks.

**Comment by ForelaxX** [comment]
@mostafaeweda What the day you will release the latest Nuclide? I can't wait to debug with Nuclide~

**Comment by mostafaeweda** [comment]
Next week, most-likely Tuesday, November 28th

**Comment by pelmers** [comment]
@minhduc200585 sorry, a little one word bug in the 270 release prevented the menu option from appearing, but it is fixed for next time in https://github.com/facebook/nuclide/commit/7d568b475444e01ec7a9da2df8c889609a230420

**Comment by noumantahir** [comment]
hey any update on this so far...? or is there any hack to debug react native within react?

**Comment by radjivF** [comment]
Any update because the debugger is not working either for me

**Comment by tumanov-alex** [comment]
So you dropped the support, but left the button for react native debugger to confuse everyone?

**Comment by sitefeng** [comment]
Trying to get the debugger to attach to react native app for the first time, but the attach button fails without any errors. Looks like the feature is still not working.

**Comment by DimonLuk** [comment]
No progress even for today
